# Generated by Django 5.0.4 on 2024-05-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscript',
            field=models.BooleanField(default=False),
        ),
    ]
