# Generated by Django 5.0.4 on 2024-05-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_code_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='code_1_used',
        ),
        migrations.AddField(
            model_name='code_1',
            name='code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='code_1',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
