# Generated by Django 5.0.4 on 2024-05-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_code_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
