# Generated by Django 5.0.4 on 2024-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment'),
        ('users', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userprofile',
            field=models.ManyToManyField(blank=True, related_name='love_posts', to='users.userprofile'),
        ),
    ]
