# Generated by Django 5.0.4 on 2024-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='post',
            name='lovepoint',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
